# Generated by Django 4.1.2 on 2024-12-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
