# Generated by Django 4.1.2 on 2024-03-20 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proof_file",
                    models.FileField(default="proof/myfile.pdf", upload_to="proof/"),
                ),
                (
                    "proof_choice",
                    models.CharField(
                        choices=[("aadhar", "aadhar"), ("voter", "voter")],
                        default="aadhar",
                        max_length=9,
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_account_no", models.CharField(max_length=255)),
                ("bank_branch", models.CharField(max_length=255)),
                ("bank_ifsc", models.CharField(max_length=255)),
                ("upi_id", models.CharField(max_length=255)),
                (
                    "bank_proof_choice",
                    models.CharField(
                        choices=[
                            ("cheque", "cheque"),
                            ("passbook", "passbook"),
                            ("statement", "statement"),
                        ],
                        default="aadhar",
                        max_length=9,
                    ),
                ),
                (
                    "bank_proof_file",
                    models.FileField(default="proof/myfile.pdf", upload_to="proof/"),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
