# Generated by Django 4.1.2 on 2024-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="avatar.jpg", upload_to="profile_avatars/"),
        ),
    ]
