# Generated by Django 4.1.2 on 2024-04-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_kyc_bank_account_no_alter_kyc_bank_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kyc",
            name="bank_account_no",
        ),
        migrations.RemoveField(
            model_name="kyc",
            name="bank_branch",
        ),
        migrations.RemoveField(
            model_name="kyc",
            name="bank_ifsc",
        ),
        migrations.RemoveField(
            model_name="kyc",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="kyc",
            name="bank_proof_choice",
        ),
        migrations.RemoveField(
            model_name="kyc",
            name="bank_proof_file",
        ),
        migrations.RemoveField(
            model_name="kyc",
            name="upi_id",
        ),
    ]
