# Generated by Django 4.1.2 on 2024-04-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_kyc_bank_account_no_remove_kyc_bank_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(default="avatar.jpg", upload_to="home_banner/"),
                ),
            ],
        ),
    ]
