# Generated by Django 4.1.2 on 2024-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_homebanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide", models.ImageField(default="avatar.jpg", upload_to="slide/")),
            ],
        ),
    ]
