# Generated by Django 4.1.2 on 2024-04-10 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_slider"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChitActivities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("act_date", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StockLastestNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_date", models.DateField(default=datetime.datetime.now)),
                ("stock_name", models.CharField(max_length=255)),
                ("event_details", models.CharField(max_length=255)),
                ("trend", models.CharField(max_length=255)),
            ],
        ),
    ]
