# Generated by Django 4.1.2 on 2024-04-10 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_chitactivities_stocklastestnews"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitactivities",
            name="act_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chitactivities",
            name="act_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
