# Generated by Django 4.1.2 on 2024-04-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_chitactivities_act_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklastestnews",
            name="stock_pic",
            field=models.ImageField(default="avatar.jpg", upload_to="stock_pic/"),
        ),
    ]
