# Generated by Django 4.1.2 on 2024-04-15 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_stocklastestnews_stock_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="homebanner",
            name="banner_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
