# Generated by Django 4.1.2 on 2024-05-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_homebanner_banner_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerBankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_account_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bank_ifsc", models.CharField(blank=True, max_length=255, null=True)),
                ("upi_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_proof_choice",
                    models.CharField(
                        choices=[
                            ("cheque", "cheque"),
                            ("passbook", "passbook"),
                            ("statement", "statement"),
                        ],
                        default="aadhar",
                        max_length=9,
                    ),
                ),
                (
                    "bank_proof_file",
                    models.FileField(
                        blank=True,
                        default="proof/myfile.pdf",
                        null=True,
                        upload_to="proof/",
                    ),
                ),
            ],
        ),
    ]
