# Generated by Django 4.1.2 on 2024-05-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_customerbankdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpcomingDividends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "announcement_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("divd_type", models.CharField(blank=True, max_length=255, null=True)),
                ("ex_date", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "record_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dps", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "div_percentage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
