# Generated by Django 4.1.2 on 2024-05-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_upcomingdividends"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsefullLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_name", models.CharField(blank=True, max_length=255, null=True)),
                ("site_link", models.URLField(max_length=1000)),
            ],
        ),
    ]
