# Generated by Django 4.1.2 on 2024-05-23 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_incomeexpenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomeexpenses",
            name="entry_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
