# Generated by Django 4.1.2 on 2024-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_lotteryspinlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="upcomingdividends",
            name="stock_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
