# Generated by Django 4.1.2 on 2024-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_upcomingdividends_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upcomingdividends",
            name="action",
            field=models.IntegerField(
                blank=True, default=-1, max_length=255, null=True
            ),
        ),
    ]
