# Generated by Django 4.1.2 on 2024-06-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_upcomingdividends_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="videofile",
            field=models.FileField(
                null=True, upload_to="deploy/videos/", verbose_name=""
            ),
        ),
    ]
