# Generated by Django 4.1.2 on 2024-06-19 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0023_alter_slider_videofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="P2PRequestForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proof_file",
                    models.FileField(
                        blank=True,
                        default="proof/myfile.pdf",
                        null=True,
                        upload_to="proof/",
                    ),
                ),
                (
                    "proof_choice",
                    models.CharField(
                        choices=[("aadhar", "aadhar"), ("voter", "voter")],
                        default="aadhar",
                        max_length=9,
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
