# Generated by Django 4.1.2 on 2024-06-19 10:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chit", "0012_chitpaymentnotification_chit_details_and_more"),
        ("home", "0024_p2prequestform"),
    ]

    operations = [
        migrations.AddField(
            model_name="p2prequestform",
            name="chit_amount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chit.chitdetails",
            ),
        ),
        migrations.AddField(
            model_name="p2prequestform",
            name="credit_status",
            field=models.CharField(
                choices=[
                    ("CLOSE", "CLOSE"),
                    ("PRE-CLOSE", "PRE-CLOSE"),
                    ("OPEN", "OPEN"),
                    ("REJECT", "REJECT"),
                    ("IN-PROCESS", "IN-PROCESS"),
                ],
                default="IN-PROCESS",
                max_length=39,
            ),
        ),
        migrations.AddField(
            model_name="p2prequestform",
            name="disburment_amount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="p2prequestform",
            name="eligibility_amount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="p2prequestform",
            name="emi_amount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="p2prequestform",
            name="entry_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="p2prequestform",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="p2prequestform",
            name="no_of_months",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="p2prequestform",
            name="processing_charges",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="P2PCreditEMI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_file",
                    models.FileField(
                        blank=True,
                        default="proof/myfile.pdf",
                        null=True,
                        upload_to="proof/",
                    ),
                ),
                (
                    "emi_choice",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3")],
                        default="aadhar",
                        max_length=9,
                    ),
                ),
                (
                    "chit_amount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chit.chitdetails",
                    ),
                ),
                (
                    "p2prequest_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.p2prequestform",
                    ),
                ),
            ],
        ),
    ]
