# Generated by Django 4.1.2 on 2024-06-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_p2prequestform_chit_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpensesList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField()),
            ],
        ),
    ]
