# Generated by Django 4.1.2 on 2024-07-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "home",
            "0028_rename_proof_choice_p2prequestform_address_proof_choice_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="p2prequestform",
            name="loan_status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "APPROVED"),
                    ("REJECT", "REJECT"),
                    ("IN-PROCESS", "IN-PROCESS"),
                ],
                default="IN-PROCESS",
                max_length=39,
            ),
        ),
        migrations.AlterField(
            model_name="p2prequestform",
            name="credit_status",
            field=models.CharField(
                choices=[
                    ("CLOSE", "CLOSE"),
                    ("PRE-CLOSE", "PRE-CLOSE"),
                    ("ACTIVE", "ACTIVE"),
                    ("REJECT", "REJECT"),
                    ("IN-PROCESS", "IN-PROCESS"),
                    ("DISBURSEMENT", "DISBURSEMENT"),
                ],
                default="IN-PROCESS",
                max_length=39,
            ),
        ),
    ]
