# Generated by Django 4.1.2 on 2024-07-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_p2prequestform_loan_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="p2prequestform",
            name="disbursment_proof_file",
            field=models.FileField(
                blank=True, default="proof/myfile.pdf", null=True, upload_to="proof/"
            ),
        ),
    ]
