# Generated by Django 4.1.2 on 2024-07-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_p2prequestform_disbursment_proof_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="p2prequestform",
            name="customer_disbursment_recived_file",
            field=models.FileField(
                blank=True, default="proof/myfile.pdf", null=True, upload_to="proof/"
            ),
        ),
    ]
