# Generated by Django 4.1.2 on 2024-10-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_p2prequestform_customer_disbursment_recived_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="p2pcreditemi",
            name="payment_choice",
            field=models.CharField(
                choices=[("NotPaid", "NotPaid"), ("Paid", "Paid")],
                default="NotPaid",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="p2pcreditemi",
            name="emi_choice",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                ],
                default="aadhar",
                max_length=9,
            ),
        ),
    ]
