# Generated by Django 4.1.2 on 2024-10-03 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_alter_p2pcreditemi_payment_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="P2PPaymentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p2p_amount", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment_choice",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_month",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "p2prequest_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.p2prequestform",
                    ),
                ),
            ],
        ),
    ]
