# Generated by Django 4.1.2 on 2024-10-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_p2ppaymentnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="p2pcreditemi",
            name="p2p_amount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
