# Generated by Django 4.1.2 on 2024-10-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0039_p2pcreditemi_p2p_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="p2ppaymentnotification",
            name="p2prequest_obj",
        ),
        migrations.AddField(
            model_name="p2ppaymentnotification",
            name="p2ploan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
