# Generated by Django 4.1.2 on 2024-03-14 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chit", "0003_customerchitplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerChitPaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chit_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("January", "January"),
                            ("Feburary", "Feburary"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        default="January",
                        max_length=9,
                    ),
                ),
                ("chit_year", models.CharField(blank=True, max_length=255)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("NotPaid", "NotPaid"), ("Paid", "Paid")],
                        default="NotPaid",
                        max_length=9,
                    ),
                ),
                ("trans_id", models.CharField(default="", max_length=555)),
                (
                    "payment_file",
                    models.FileField(
                        default="paymentfiles/myfile.pdf", upload_to="paymentfiles/"
                    ),
                ),
                ("amount_paid", models.CharField(default=0.0, max_length=255)),
                ("payment_date", models.DateField(default=datetime.datetime.now)),
                (
                    "chit_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chit.chitdetails",
                    ),
                ),
                (
                    "customer_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
