# Generated by Django 4.1.2 on 2024-03-19 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chit", "0004_customerchitpaymentdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollChit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enroll_status",
                    models.CharField(
                        choices=[
                            ("Auction", "Auction"),
                            ("Participate", "Participate"),
                            ("NA", "NA"),
                        ],
                        default="NA",
                        max_length=29,
                    ),
                ),
                (
                    "admin_per_status",
                    models.CharField(
                        choices=[
                            ("Accept", "Accept"),
                            ("NotAccept", "NotAccept"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=29,
                    ),
                ),
                (
                    "chit_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chit.chitdetails",
                    ),
                ),
                (
                    "customer_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
