# Generated by Django 4.1.2 on 2024-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chit", "0005_enrollchit"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollchit",
            name="chit_month_count",
            field=models.CharField(default=0, max_length=255),
        ),
    ]
