# Generated by Django 4.1.2 on 2024-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chit", "0006_enrollchit_chit_month_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitdetails",
            name="chit_disbursedate_month",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="chitdetails",
            name="chit_duedate_month",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
