# Generated by Django 4.1.2 on 2024-05-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chit", "0007_chitdetails_chit_disbursedate_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitdetails",
            name="chit_enrolldate_month",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
