# Generated by Django 4.1.2 on 2024-05-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chit", "0008_chitdetails_chit_enrolldate_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerchitpaymentdetails",
            name="chit_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--"),
                    ("January", "January"),
                    ("Feburary", "Feburary"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default="January",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="monthwisechitdetails",
            name="chit_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--"),
                    ("January", "January"),
                    ("Feburary", "Feburary"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default="",
                max_length=9,
            ),
        ),
    ]
