# Generated by Django 4.1.2 on 2024-07-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chit", "0012_chitpaymentnotification_chit_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitdetails",
            name="chit_isstarted",
            field=models.BooleanField(default=False, verbose_name="Chit Started"),
        ),
    ]
