# Generated by Django 4.1.2 on 2024-08-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chit", "0015_monthwisechitdetails_agent_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerchitpaymentdetails",
            name="amount_need_to_pay",
            field=models.CharField(default=0.0, max_length=255),
        ),
    ]
