# Generated by Django 4.1.2 on 2024-08-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chit", "0016_customerchitpaymentdetails_amount_need_to_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitdetails",
            name="chit_type",
            field=models.CharField(
                blank=True,
                choices=[("Regular", "Regular"), ("Continuous", "Continuous")],
                default="Regular",
                max_length=100,
            ),
        ),
    ]
