# Generated by Django 4.1.2 on 2024-08-31 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chit", "0017_chitdetails_chit_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContinuousChitWinner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wining_chit_count",
                    models.CharField(blank=True, default="", max_length=9),
                ),
                ("get_chit_amount", models.CharField(max_length=255)),
                (
                    "disburment_pic",
                    models.ImageField(
                        default="avatar.jpg", upload_to="disburment_pic/"
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        choices=[("", "--"), ("Online", "Online"), ("Cash", "Cash")],
                        default="",
                        max_length=9,
                    ),
                ),
                (
                    "agent_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chit.agentlist",
                    ),
                ),
                (
                    "chit_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chit.chitdetails",
                    ),
                ),
                (
                    "winner_of_chit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContinuousChitDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chit_count", models.CharField(blank=True, default="", max_length=9)),
                ("get_chit_amount", models.CharField(max_length=255)),
                (
                    "chit_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chit.chitdetails",
                    ),
                ),
            ],
        ),
    ]
