# Generated by Django 4.1.2 on 2024-12-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chit", "0018_continuouschitwinner_continuouschitdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerchitplan",
            name="start_chit_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--"),
                    ("January", "January"),
                    ("Feburary", "Feburary"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default="January",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="customerchitplan",
            name="start_chit_year",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
