# Generated by Django 4.1.2 on 2024-04-16 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0002_dividendtrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="swingtrade",
            name="report_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
