# Generated by Django 4.1.2 on 2024-04-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0003_swingtrade_report_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="swingtrade",
            name="trade_choice",
            field=models.CharField(
                choices=[("SWING", "SWING"), ("INTRADAY", "INTRADAY")],
                default="SWING",
                max_length=9,
            ),
        ),
    ]
