# Generated by Django 4.1.2 on 2024-04-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0004_swingtrade_trade_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="swingtrade",
            name="trend_choice",
            field=models.CharField(
                choices=[("BULLISH", "BULLISH")], default="BULLISH", max_length=9
            ),
        ),
    ]
