# Generated by Django 4.1.2 on 2024-04-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0005_swingtrade_trend_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="dividendtrade",
            name="dividend_share",
            field=models.CharField(default="", max_length=255),
        ),
    ]
