# Generated by Django 4.1.2 on 2024-04-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0006_dividendtrade_dividend_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="dividendtrade",
            name="dividend_yield",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="dividendtrade",
            name="yield_msg",
            field=models.CharField(default="", max_length=255),
        ),
    ]
