# Generated by Django 4.1.2 on 2024-04-26 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0008_dividendtrade_record_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="swingtrade",
            name="hold_upto_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="swingtrade",
            name="stock_buy_price",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="swingtrade",
            name="stock_title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
