# Generated by Django 4.1.2 on 2024-04-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0009_swingtrade_hold_upto_date_swingtrade_stock_buy_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="swingtrade",
            name="stock_sell_price",
            field=models.CharField(default="", max_length=255),
        ),
    ]
