# Generated by Django 4.1.2 on 2024-04-26 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("share", "0010_swingtrade_stock_sell_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_choice",
                    models.CharField(
                        choices=[
                            ("FREE", "FREE"),
                            ("STANDARD", "STANDARD"),
                            ("ADVANCE", "ADVANCE"),
                        ],
                        default="FREE",
                        max_length=9,
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
